// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: protos/cluster/cluster.proto

package cluster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_protos_cluster_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cluster_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_protos_cluster_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_protos_cluster_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cluster_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_protos_cluster_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

var File_protos_cluster_cluster_proto protoreflect.FileDescriptor

const file_protos_cluster_cluster_proto_rawDesc = "" +
	"\n" +
	"\x1cprotos/cluster/cluster.proto\x12\acluster\"\x1a\n" +
	"\x04Ping\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\"\x19\n" +
	"\x03Ack\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from29\n" +
	"\x0eClusterService\x12'\n" +
	"\bPingNode\x12\r.cluster.Ping\x1a\f.cluster.AckB\x12Z\x10/cluster;clusterb\x06proto3"

var (
	file_protos_cluster_cluster_proto_rawDescOnce sync.Once
	file_protos_cluster_cluster_proto_rawDescData []byte
)

func file_protos_cluster_cluster_proto_rawDescGZIP() []byte {
	file_protos_cluster_cluster_proto_rawDescOnce.Do(func() {
		file_protos_cluster_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_cluster_cluster_proto_rawDesc), len(file_protos_cluster_cluster_proto_rawDesc)))
	})
	return file_protos_cluster_cluster_proto_rawDescData
}

var file_protos_cluster_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_cluster_cluster_proto_goTypes = []any{
	(*Ping)(nil), // 0: cluster.Ping
	(*Ack)(nil),  // 1: cluster.Ack
}
var file_protos_cluster_cluster_proto_depIdxs = []int32{
	0, // 0: cluster.ClusterService.PingNode:input_type -> cluster.Ping
	1, // 1: cluster.ClusterService.PingNode:output_type -> cluster.Ack
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_cluster_cluster_proto_init() }
func file_protos_cluster_cluster_proto_init() {
	if File_protos_cluster_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_cluster_cluster_proto_rawDesc), len(file_protos_cluster_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_cluster_cluster_proto_goTypes,
		DependencyIndexes: file_protos_cluster_cluster_proto_depIdxs,
		MessageInfos:      file_protos_cluster_cluster_proto_msgTypes,
	}.Build()
	File_protos_cluster_cluster_proto = out.File
	file_protos_cluster_cluster_proto_goTypes = nil
	file_protos_cluster_cluster_proto_depIdxs = nil
}
